cabal-version:      2.4
name:               jblog
version:            0.1.0.0
build-type:         Simple
tested-with:        GHC == 9.10.1

executable site
  main-is:          site.hs
  build-depends:    base >= 4.14 && < 5
                  , binary
                  , bytestring
                  , hakyll >= 4.16 && < 5
                  , process
  ghc-options:      -threaded -rtsopts -with-rtsopts=-N
  default-language: Haskell2010
