#!/usr/bin/env python3

import argparse
from datetime import datetime
import os
import pathlib


def make_filename(args):
    root_dir = pathlib.Path(__file__).parent.resolve()
    directory_name = 'slush' if args.slush else 'posts'
    timestamp = datetime.now().strftime('%Y-%m-%d')
    filename = '{}--{}.md'.format(timestamp, '-'.join(args.title))
    return os.path.join(root_dir, directory_name, filename)


STUB = '''---
title: {title}
tags: stuff, things
---

# {title}
'''


def write_stub(filename, title):
    with open(filename, 'w') as f:
        f.write(STUB.format(title=' '.join(title)))


parser = argparse.ArgumentParser(
    description='Create a stub for a new post.',
    epilog='Example: ./stub rubik group')
parser.add_argument(
    'title', nargs='+', help='a short title used for the filename')
parser.add_argument(
    '-s', '--slush', action='store_true',
    help='create a slush post')
args = parser.parse_args()

filename = make_filename(args)
write_stub(filename, args.title)
print('Created', filename)
